### ISSUE TITLE
Set up localization on Weblate

### ISSUE THREAD

**Issue by danirabbit** [elementary/bluetooth-daemon#3]
Need to make a new project component for desktop and import

**Comment by danirabbit** [comment]
https://l10n.elementary.io/projects/desktop/bluetooth-daemon/

https://l10n.elementary.io/projects/desktop/bluetooth-daemon-extra/

**Comment by ryonakano** [comment]
Hmm looks like Weblate is failing to push to the repository:

![Screenshot from 2024-07-20 15-49-31](https://github.com/user-attachments/assets/6481e940-f46c-4d1c-ba50-948c962a6ccf)

**Comment by danirabbit** [comment]
Ah probably branch protection rules. Re-opening so I remember to figure it out :)

**Comment by ryonakano** [comment]
Looks like @tintou fixed this? It's now possible to push Weblate changes to the repository.
